const Shift = require("../models/Shift");

/**
 * Timetable is the only scheduler. This service reads the materialized shift rows
 * (generated by timetable saves) so attendance can evaluate late/unscheduled.
 */
async function getClockWindowForToday(staffId, todayYmd) {
  return Shift.findOne({ staff_id: staffId, shift_date: todayYmd }).lean();
}

module.exports = { getClockWindowForToday };

